#Arm_vision_planning.action 内容
# 请求数据，视觉系统->机械臂系统
# 视觉系统是client, 机械臂是server
int32      hand_no                           # hand_no=1, 表示左手；hand_no=2, 表示右手
int32[2]   hand                              #hand[0]: 取还是放的动作，0： 拾取，1：放。              hand[1]:动作序列编号
#int32      command_no                        # 当前指令的编号，从1开始。代表第几条指令
---
# 结果反馈，机械臂系统->视觉系统
int32      hand_no                           # hand_no=1, 表示左手；hand_no=2, 表示右手
#int32      command_no                        # 当前指令的编号，从1开始。代表第几条指令
float32[6]    hand_pose                 #手的6自由度关节实际角度
bool success 
string info                             # error_info if success is false else is empty
---
# 过程反馈，机械臂系统->视觉系统
int32      hand_no                           # hand_no=1, 表示左手；hand_no=2, 表示右手
#int32      command_no                        # 当前指令的编号，从1开始。代表第几条指令
float32[6]   hand_pose                  # 手的6自由度关节实际角度
