# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    jaka_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

jaka_arm_controller:
  ros__parameters:
    joints:
      - r-j1_right
      - r-j2_right
      - r-j3_right
      - r-j4_right
      - r-j5_right
      - r-j6_right
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity