# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - jaka_arm_controller

  jaka_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - r-j1_right
      - r-j2_right
      - r-j3_right
      - r-j4_right
      - r-j5_right
      - r-j6_right